apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-server
spec:
  selector:
    app: auth-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort