apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  SPRING_PROFILES_ACTIVE: docker
  AUTH_SERVER_URL: http://auth-service:8081/auth
  DATABASE_URL: jdbc:postgresql://postgres:5432/fmdDB