apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: api-gateway-config
        - name: secret-volume
          secret:
            secretName: api-gateway-secret
        - name: shared-data
          emptyDir: {}
      initContainers:
        - name: init-config
          image: busybox
          command: ['sh', '-c', 'echo Initializing API Gateway...']
          volumeMounts:
            - name: shared-data
              mountPath: /data
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      containers:
        - name: api-gateway
          image: api-gateway:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: SPRING_PROFILES_ACTIVE
            - name: AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: AUTH_SERVER_URL
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: DATABASE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: secret-volume
              mountPath: /secrets
            - name: shared-data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"