
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/aidoc_postgres_db
    username: aidoc_user
    password: aidoc_password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update